GET http://localhost:8080/php/use/get.php HTTP/1.1
content-type: application/json
###

GET http://localhost/perudonline/src/php/use/get.php HTTP/1.1
content-type: application/json
###

POST http://localhost/perudonline/src/php/use/post.php  HTTP/1.1
content-type: application/json

{
    "table": "test",
    "prenom": "Josette",
    "nom": "Pastis",
    "genre": "f"
}
###

PUT http://localhost/perudonline/src/php/use/update.php  HTTP/1.1
content-type: application/json

{
    "table": "test",
    "prenom": "Bernard",
    "nom": "Pastaga",
    "genre": "m"
}